### ISSUE TITLE
[FEAT] 회원가입 시 포인트 지급

### ISSUE THREAD

**Issue by JJadeYoon** [UMC-beilsang/Beilsang-Server#171]
# ✨ Feature -  회원 가입 시 포인트 지급 기능 구현

### 📝 Description

---

회원 가입 시 1000포인트, 추천인 등록 시 500 포인트를 지급하는 기능을 추가한다.
또한 PointLog를 이용해 기록을 저장한다.

### ✅ To Do List 

---

- [x] 회원 가입 서비스 수정
- [x] 주소, 알게된 경로 추천인 등록 수정

**Comment by fewolee** [comment]
주소,
